edits to notebooks 4 and 7
RTIInternational/all_of_us_python_course pull request #4
Opened 2024-07-09 14:12 UTC by jon-holt

- Edits to notebooks 4 and 7

2024-07-09 18:20 UTC, michael-long88 requested changes
Everything is running that should be running and the appropriate cells are throwing errors. I just left one comment, but other than that, it looks good!

2024-07-09 18:20 UTC, michael-long88 commented on content/Main_Notebooks/4 - Simple Filtering.ipynb
> +    "There are other ways to connect expressions. `&` handles \"and\", meaning both parts have to be true. `|` (which you can generally type as Shift+\\) means \"or\", meaning at least one of the par
Not sure why, but it looks like the first slash in "(which you can generally type as Shift+\\)" got dropped when looking at in the browser, so it just looks like "(which you can generally type as Shift+)". Wrapping shift and \ in ` seems to fix the issue if both slashes are still showing up for you locally.

2024-07-09 21:08 UTC, jon-holt commented on content/Main_Notebooks/4 - Simple Filtering.ipynb
> +    "There are other ways to connect expressions. `&` handles \"and\", meaning both parts have to be true. `|` (which you can generally type as Shift+\\) means \"or\", meaning at least one of the par
You're right, it looks like the extra "\" got dropped. I just added it back in. See if this looks better.

2024-07-10 20:11 UTC, michael-long88 approved these changes
Looks good now!

2024-07-10 20:11 UTC, merged